"""Add cover image to club edit requests

Revision ID: 3271da9ece65
Revises: 3c0641830866
Create Date: 2026-08-26 23:23:04.405540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3271da9ece65'
down_revision = '3c0641830866'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('club_edit_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_image_filename', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('club_edit_requests', schema=None) as batch_op:
        batch_op.drop_column('cover_image_filename')

    # ### end Alembic commands ###
