"""Create clubs tables

Revision ID: 3c0641830866
Revises: 2d994383a3a3
Create Date: 2026-08-18 18:29:15.324448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c0641830866'
down_revision = '2d994383a3a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('club_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('short_description', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('president_name', sa.String(length=120), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=False),
    sa.Column('instagram', sa.String(length=120), nullable=True),
    sa.Column('cover_image_filename', sa.String(length=255), nullable=True),
    sa.Column('requester_name', sa.String(length=120), nullable=False),
    sa.Column('requester_email', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clubs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('short_description', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('president_name', sa.String(length=120), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=False),
    sa.Column('instagram', sa.String(length=120), nullable=True),
    sa.Column('cover_image_filename', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('club_edit_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('short_description', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('president_name', sa.String(length=120), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=False),
    sa.Column('instagram', sa.String(length=120), nullable=True),
    sa.Column('requester_name', sa.String(length=120), nullable=False),
    sa.Column('requester_email', sa.String(length=255), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('club_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('image_filename', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('club_images')
    op.drop_table('club_edit_requests')
    op.drop_table('clubs')
    op.drop_table('club_requests')
    # ### end Alembic commands ###
